language: php
php:
  - '5.5'
  - '6.5'
  - '7.1'
  - '7.2'
  - 'hhvm'
  - 'nightly'
services: 
  -mysql
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo service apache2 restart
  - composer install
  - composer global require phpunit/phpunit
  - mysql -e 'CREATE DATABASE IF NOT EXISTS blog;'
  - php artisan migrate
script:
  - phpunit
  