language: php
php:
  - 5.5
  - 6.5
  - 7.0
  - 7.1
  - 7.2
services: 
  -mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS blog;'
before_script:
  - composer install
  - composer update
  - composer global require phpunit/phpunit
  - php artisan migrate
script:
  - phpunit

